name: servant-prometheus
version: 1.3.0
github: worm2fed/servant-prometheus
synopsis: Helpers for using prometheus with servant
description: Please see the README on GitHub at <https://github.com/worm2fed/servant-prometheus#readme>
category: Servant, Web, System
license: BSD-3-Clause
license-file: LICENSE
author: Andrii Demydenko <worm2fed@gmail.com>, Anchor Engineering <engineering@lists.anchor.net.au>, Servant Contributors
maintainer: Andrii Demydenko <worm2fed@gmail.com>

extra-source-files:
  - README.md
  - LICENSE

extra-doc-files:
  - CHANGELOG.md

tested-with:
  - GHC == 9.2.8
  - GHC == 9.4.7
  - GHC == 9.4.8

verbatim:
  cabal-version: 2.4

# GHC's GHC2021 language extension is supported by GHC >= 9.2.1
# for more details see: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst
language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedStrings
  - RecordWildCards
  - UndecidableInstances

ghc-options:
  # For details on warnings:
  # https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html

  # Enable all warnings and disable the ones we don’t care about
  - -Weverything

  # Turns off the more strict -Wmissing-signatures
  # See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-exported-signatures
  # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missing-import-lists
  # When GHC can’t specialize a polymorphic function. No big deal and requires
  # fixing underlying libraries to solve
  - -Wno-missed-specialisations
  # See missed-specialisations
  - -Wno-all-missed-specialisations
  # Don’t use Safe Haskell warnings
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-inferred-safe-imports
  - -Wno-missing-safe-haskell-mode
  # Warning for polymorphic local bindings; nothing wrong with those
  - -Wno-missing-local-signatures
  # Don’t warn if the monomorphism restriction is used
  - -Wno-monomorphism-restriction
  # Still need it, because generated cabal module uses prepositive position
  - -Wno-prepositive-qualified-module
  # Do not warn about missing kind signatures; there is no much sense for it
  # now, our project is not so type-complicated.
  - -Wno-missing-kind-signatures
  # Do not warn about implicit prelude since we use default one
  - -Wno-implicit-prelude

dependencies:
  - base >=4.10 && < 4.21

library:
  source-dirs: lib
  dependencies:
    - clock >= 0.8.3 && < 0.9
    - ghc-prim >= 0.8.0 && < 0.12
    - hashable >= 1.4.2 && < 1.6
    - http-types >= 0.12.3 && < 0.13
    - prometheus-client >= 1.1.0 && < 1.2
    - servant >= 0.14 && < 0.21
    - text >= 1.2.5 && < 2.2
    - wai >= 3.2.3 && < 3.3

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    build-tools: hspec-discover:hspec-discover
    ghc-options:
      - -Wno-missing-export-lists
      - -threaded
      - '"-with-rtsopts=-N -A64m -AL256m"'
    dependencies:
      - servant-prometheus

      - aeson >= 2.0 && < 2.3
      - containers >= 0.6.5 && < 0.8
      - hspec >= 2 && < 3
      - hspec-expectations-pretty-diff >= 0.7.2.2 && < 0.8
      - http-client >= 0.7.13 && < 0.8
      - http-types >=0.12.4 && <0.13
      - prometheus-client
      - servant
      - servant-client >= 0.14 && < 0.21
      - servant-server >= 0.14 && < 0.21
      - text
      - wai
      - warp >= 3.2.4 && < 3.5

benchmarks:
  bench:
    source-dirs: bench
    main: Main.hs
    ghc-options:
      - -threaded
      - '"-with-rtsopts=-N -A64m -AL256m"'
    dependencies:
      - process >= 1.6.16 && < 1.7
      - servant-prometheus
      - servant-server
      - text
      - wai
      - warp
